services:
  bajacloud:
    container_name: darkicewolf50cloud
    image: darkicewolf50/darkicewolf50cloud:latest
    # restart: unless-stopped
    build: . # do not include in delpoyment version
    ports:
      - 5050:5050
    volumes:
      - ./database:/database
      - ./blogs:/blogs
